#!/bin/bash

gphoto2 \
    --camera='Canon EOS 7D MarkII' --set-config viewfinder=1 \
    --camera='Canon EOS 7D MarkII' --wait-event 1000ms \
    --camera='Canon EOS 7D MarkII' --set-config drivemode=2 \
    --camera='Canon EOS 7D MarkII' --set-config shutterspeed=1/1000 \
    --camera='Canon EOS 7D MarkII' --set-config eosremoterelease=5 \
    --camera='Canon EOS 7D MarkII' --wait-event 1300ms \
    --camera='Canon EOS 7D MarkII' --set-config eosremoterelease=4 \
    --camera='Canon EOS 7D MarkII' --set-config eosremoterelease=5 \
    --camera='Canon EOS 7D MarkII' --wait-event 1300ms \
    --camera='Canon EOS 7D MarkII' --set-config eosremoterelease=4 \
    --camera='Canon EOS 7D MarkII' --set-config eosremoterelease=5 \
    --camera='Canon EOS 7D MarkII' --wait-event 1300ms \
    --camera='Canon EOS 7D MarkII' --set-config eosremoterelease=4 \
    --camera='Canon EOS 7D MarkII' --set-config eosremoterelease=5 \
    --camera='Canon EOS 7D MarkII' --wait-event 1300ms \
    --camera='Canon EOS 7D MarkII' --set-config eosremoterelease=4 \
    --camera='Canon EOS 7D MarkII' --set-config eosremoterelease=5 \
    --camera='Canon EOS 7D MarkII' --wait-event 1300ms \
    --camera='Canon EOS 7D MarkII' --set-config eosremoterelease=4 \
    --camera='Canon EOS 7D MarkII' --set-config eosremoterelease=5 \
    --camera='Canon EOS 7D MarkII' --wait-event 1300ms \
    --camera='Canon EOS 7D MarkII' --set-config eosremoterelease=4 \
    --camera='Canon EOS 7D MarkII' --set-config eosremoterelease=5 \
    --camera='Canon EOS 7D MarkII' --wait-event 1300ms \
    --camera='Canon EOS 7D MarkII' --set-config eosremoterelease=4 \
    --camera='Canon EOS 7D MarkII' --set-config eosremoterelease=5 \
    --camera='Canon EOS 7D MarkII' --wait-event 1300ms \
    --camera='Canon EOS 7D MarkII' --set-config eosremoterelease=4 \
    --camera='Canon EOS 7D MarkII' --set-config eosremoterelease=5 \
    --camera='Canon EOS 7D MarkII' --wait-event 1300ms \
    --camera='Canon EOS 7D MarkII' --set-config eosremoterelease=4 \
    --camera='Canon EOS 7D MarkII' --set-config eosremoterelease=5 \    
