#!/bin/bash

gphoto2 \
    --trigger-capture \
    --trigger-capture \
    --trigger-capture \
    --trigger-capture \
    --trigger-capture \
    --trigger-capture \
    --trigger-capture \
    --trigger-capture \
    --trigger-capture \
    --trigger-capture \
    --trigger-capture \
    --trigger-capture \
    --trigger-capture \
    --trigger-capture \
    --trigger-capture \
    --trigger-capture \
    --trigger-capture \
    --trigger-capture \
    --trigger-capture \
    --trigger-capture \
    --trigger-capture \
    --trigger-capture \
    --trigger-capture \
    --trigger-capture \
    --trigger-capture \
    --trigger-capture \
    --trigger-capture \
